### ISSUE TITLE
Code snippet in Wiki breaks microphone on iOS SetCategory(AVAudioSessionCategory.Playback) 

### ISSUE THREAD

**Issue by rburnashev85** [jfversluis/Plugin.Maui.Audio#87]
```
#if IOS
    AVFoundation.AVAudioSession.SharedInstance().SetCategory(AVAudioSessionCategory.Playback);
#endif
```

I experienced microphone issues on iOS using Azure speech services after I ran this code snipped. 

https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2188

**Comment by bijington** [comment]
Why are you using the above code snippet?

Anyway the issue is because it is changing the overall category for media. You will need to undo this change once you have finished using it for whatever purpose it is. Or find an alternative option from `AVAudioSessionCategory`.

That being said I would like to investigate how we could provide a mechanism to change values like this easily

**Comment by rburnashev85** [comment]
I used it to make audio play in iPhone's silent mode as it is described in your wiki https://github.com/jfversluis/Plugin.Maui.Audio/wiki

**Comment by bijington** [comment]
For now a workaround would be to keep track of what `AVFoundation.AVAudioSession.SharedInstance().Category` is before you change it and then set that value back after playing the audio.
